### ISSUE TITLE
spidercat.ps1 not working

### ISSUE THREAD

**Issue by S0L1DB** [CosmodiumCS/SpiderCat#3]
----------------
At C:\Users\xxx\spidercat\spidercat.ps1:85 char:21
+         return "NA" -ErrorAction SilentlyContinue
+                     ~~~~~~~~~~~~
Unexpected token '-ErrorAction' in expression or statement.
At C:\Users\xxx\spidercat\spidercat.ps1:85 char:34
+         return "NA" -ErrorAction SilentlyContinue
+                                  ~~~~~~~~~~~~~~~~
Unexpected token 'SilentlyContinue' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
---------------

I'm getting this error while running spidercat.ps1 on a virtual machine and on other Windows 10/11 endpoints. what's wrong?

**Comment by JohannesKraggerud** [comment]
Same

**Comment by JohannesKraggerud** [comment]
> 

same

**Comment by atomiczsec** [comment]
@JohannesKraggerud @S0L1DB I have just made a pull request to fix this issue!
